--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO app;

--
-- Name: yeti; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.yeti (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    height double precision DEFAULT 0,
    weight double precision DEFAULT 0,
    image character varying(255) DEFAULT NULL::character varying,
    votes integer DEFAULT 0 NOT NULL,
    vote_timestamp timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created timestamp(0) without time zone NOT NULL,
    modified timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.yeti OWNER TO app;

--
-- Name: yeti_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.yeti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.yeti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20250622092218	2025-06-22 09:27:47	16
\.


--
-- Data for Name: yeti; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.yeti (id, name, description, height, weight, image, votes, vote_timestamp, created, modified) FROM stdin;
89	Václav	Vyskytuje se v Labském dole, je plachý, ale prý zpívá chorály do mlhy. Při úplňku si údajně čte z kroniky Vrchlabí.	210	130	1.webp	0	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
90	Jaroslav	Žije poblíž Pece pod Sněžkou, agresivní na snowboardisty. V zimě krade horký čaj z bufetů na sjezdovce.	200	120	2.webp	4	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
91	Miloš	Zdržuje se u Dvoraček, silně aromatický yeti. Umí napodobit troubení rolby a tak mate obsluhu.	185	110	3.webp	-2	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
92	Oldřich	Obývá oblast kolem Harrachova, velmi plachý. Zajímavost: jeho srst údajně mění barvu podle počasí.	195	105	4.webp	3	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
93	Zdeněk	Přebývá na svazích kolem Rokytnice, nervózní z turistů. Rád šoupe nohama ve sněhu jako postrach běžkařů.	180	100	5.webp	1	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
94	Karel	Vyskytuje se v okolí Černé hory, mírně podrážděný. V mládí prý vyhrál místní soutěž v řevu.	205	125	6.webp	2	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
95	Josef	Stálý obyvatel Obřího dolu, velmi tichý. Prý si schovává šišky v baťohu nalezeném po turistech.	200	135	7.webp	7	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
96	Ladislav	Skrývá se v lesích nad Vrchlabím, s oblibou napodobuje zvuk motorových pil. Věčně zamrzlý vous.	185	115	8.webp	-4	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
97	Bohumil	Žije v Modrém dole, velmi samotářský. Rád skládá kamenné mohyly a pak se na ně dívá jako na TV.	190	128	9.webp	5	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
98	František	Vyskytuje se u Jánských Lázní, mírumilovný. Je známý tím, že tančí na zmrzlém listí a dělá u toho zvuky DJ pultu.	195	118	10.webp	6	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
99	Vladimír	Přebývá u Žalého, večer se vkrádá k rozhledně a sleduje hvězdy. Přes den se maskuje jako sněhulák.	198	122	11.webp	8	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
100	Stanislav	Zdržuje se v údolí Bílého Labe, velmi teritoriální. Nenávidí sáňky, přetahuje se o ně s dětmi.	202	120	12.webp	0	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
101	Antonín	Bydlí v lese nad Špindlerovým Mlýnem, zpívá opery a vytváří ledové sochy. Velký fanoušek Smetany.	210	140	13.webp	12	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
102	Rudolf	Toulá se mezi Sněžkou a Luční boudou. Agresivní jen na selfie tyče. Ovládá zneškodňování GoPro kamer.	192	117	14.webp	4	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
103	Petr	Plachý jedinec z oblasti kolem Horních Míseček. Vyrábí sněhové pasti – pro zábavu, ne pro lov.	183	101	15.webp	2	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
104	Tomáš	Zdržuje se u pramene Labe. Má rád teplé ponožky a proto je krade sušícím se turistům ze zábradlí.	186	104	16.webp	3	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
105	Roman	Výskyt kolem Medvědína. Extrovertní, píská na borovicové větve. Rád nosí klobouk z mechů.	187	109	17.webp	1	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
106	Lubomír	Obývá oblast kolem Vosecké boudy. Ve sněhu kreslí symboly, které zatím nikdo nerozluštil. Možná to jsou recepty.	200	123	18.webp	5	2025-06-22 09:54:24	2025-06-22 09:54:24	2025-06-22 09:54:24
\.


--
-- Name: yeti_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.yeti_id_seq', 106, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: yeti yeti_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.yeti
    ADD CONSTRAINT yeti_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

